module.exports = {
	title: "codesue",
	description: "Blog of Suzen Fylke.",
	url: "https://codesue.com",
	language: "en",
	locale: "en_US",
	theme_color: "hsl(0, 0%, 100%)",
	theme_color_dark: "hsl(236, 23%, 12%)",
	view_all_posts_text: "View All Posts",
	num_posts_to_display: 3,
	author: {
		name: "Suzen Fylke",
		homepage: "https://suzenfylke.com",
		blog: "https://sprakfika.se",
		microblog: "https://sigmoid.social/@suzenfylke",
		github: "https://github.com/codesue",
		linkedin: "https://linkedin.com/in/suzenfylke",
		readcv: "https://read.cv/suzenfylke",
	},
};
