[build]
	publish = "dist"
	command = "npm run build"

[[plugins]]

	# Netlify Lighthouse plugin

	package = "@netlify/plugin-lighthouse"

	[plugins.inputs.thresholds]
		performance = 0.95
		accessibility = 0.95
		best-practices = 0.95
		seo = 0.95

	[plugins.inputs]
		output_path = "reports/lighthouse/index.html"
