[build]
	publish = "dist"
	command = "npm run build"

[[plugins]]

	# Netlify Lighthouse plugin

	package = "@netlify/plugin-lighthouse"

	[plugins.inputs.thresholds]
		performance = 1.0
		accessibility = 1.0
		best-practices = 1.0
		seo = 1.0

	[plugins.inputs]
		output_path = "reports/lighthouse/index.html"
